### ISSUE TITLE
Unable to log in with mobile device

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#260] opened 2017-09-29 00:17 UTC
Using iOS 10.3.3 with Safari.

Not urgent but wondering why. Also a notice may be in order if we decide not to tackle this for the time being.

**Comment by raygesualdo** [comment] 2017-10-18 15:43
Closing because 1. it's not reproducible and 2. the underlying issue will be removed with the addition of a free plan in app-backend.

**Closed by raygesualdo** 2017-10-18 15:43 UTC
Labels: type/fix
