### ISSUE TITLE
Node error visible in browser console

### ISSUE THREAD

**Issue by jgwerner** [3Blades/react-frontend#374] opened 2017-11-07 23:17 UTC
Browser console displays node error in production:

```
You are currently using minified code outside of NODE_ENV === 'production'. 
This means that you are running a slower development build of Redux. You can 
use loose-envify (https://github.com/zertosh/loose-envify) for browserify or 
DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to 
ensure you have the correct code for your production build.
```

**Comment by raygesualdo** [comment] 2017-11-18 02:14
I was unable to reproduce. Is this still an issue?

**Comment by raygesualdo** [comment] 2017-11-27 19:37
Closing as it cannot be reproduced.

**Closed by raygesualdo** 2017-11-27 19:37 UTC
Labels: type/fix
